### PR TITLE
feat: add Blues Swan R5 support

### PR DESCRIPTION
**Pull request by bsatrom**
this would be the general Todo List based on what it took to add the F7 and H7.

- [x] Create a family category in `mpconfigport.mk`, setting all modules to 0 as per the [porting](https://circuitpython.readthedocs.io/en/latest/docs/porting.html#porting) docs.
- [x] Create a board family and SoC folder in `stm/peripherals/`, with clock setup code brought in from CubeMX, and pin/peripheral/ definitions for the SoC. Pin and peripheral files can be created with the python scripts in tools/.
- [x] Create a board folder for the first L4R5 development board in `boards/`, along with replacing appropriate pins, settings and identification information.
- [x] Create a linker file for the `L4R5` memory addresses, modified as required to allow room for an internal filesystem.
- [x] Import `system_stm32l4xx.c` from a CubeMX project and place in boards/.
- [x] Create a reduced `stm32l4xx_hal_conf.h` file in `hal_conf/` based off a CubeMX export, and add a `CPY_STM32L4` flag.
- [x] Modify the makefile to select the correct cortex settings (cortex M4), and double check that no FPU settings or other miscellaneous details need to be changed.
- [x] Add flash settings to `supervisor/internal_flash.h`.
- [x] Double check that the L4 packages in `packages/` match the ones used in the L4, and add new package definition if not.
- [x] Begin enabling modules in `common-hal/` by deleting entries `mpconfigport.mk`, starting with the easiest ones. Microcontroller and DigitalIO should need essentially no changes other than maybe an include or two, but busio typically takes more work, and AnalogIO and Pulseio take the most.

Most drivers should be brought in automatically since we have the L4 included in st-driver/. This list probably seems like more work than it actually is, most of this is just copying existing family folders/files and replacing the certain parts as necessary with the correct data from the F4R5 datasheet. The hardest part is the final section, which is adding module support in common-hal, but even a board with just DigitalIO has some utility.

### CODE REVIEW

**Comment by m-mcgowan** [comment]
Rebased onto latest from upstream repo.  During rebase, I was getting a conflict on `port/esp32s2/certificates/nina-fw` on every single commit in this PR, regardless of whether I chose "mine" or "theirs".  By squishing, I only had to resolve the conflict once.

**Comment by bsatrom** [comment]
Should we merge and make a PR against CircuitPython main @m-mcgowan m?

**Comment by m-mcgowan** [comment]
I'd like to smoke test pwmio ~and pulseio~ before saying the PR is ready to go.

**Comment by bsatrom** [comment]
Sounds good! LMK when you feel good about it and I can spot review the PR and you can do the PR against CPY main once this is merged. (You did 99.999% of the work here, so you should be the requester :D)

**Comment by m-mcgowan** [comment]
Ok, I think we're good to go with this.

**Comment by m-mcgowan** [comment]
Should we rename the branch? t5->r5? Git does support this but it will close this PR so we'll have to make a new PR here.

**Review by m-mcgowan — APPROVED** [review]

**Pull request closed without merging**
